<?php

namespace app\common\grid;

use yii\helpers\Html;

class GridView extends  \yii\grid\GridView
{

    public $modalDetail = false;
    public $detaiOptions = [];

    /**
     * {@inheritdoc}
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = '{summary}{items}{detail}{pager}';
    }
    /**
     * {@inheritdoc}
     */
    public function renderSection($name)
    {
        switch ($name) {
            case '{detail}':
                return $this->renderDetails();
            default:
                return parent::renderSection($name);
        }
    }
    public function renderDetails(){

    }
}